name: Java Spring Boot CI

on:
  push:
    branches:
    - master
    - auth

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -f pom.xml clean test

  package-and-upload:
    runs-on: ubuntu-latest
    needs: build-and-test
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -f pom.xml clean package
    - run: ls -la
    - run: ls -la target
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: backend-artifact
        path: ./target/backend-0.0.1-SNAPSHOT.jar
